# Generated by Django 2.2.6 on 2019-10-16 23:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='favorite_item',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='favorite_order',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 23, 32, 39, 327821, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersystem.CustomerAccount'),
        ),
    ]
