# Generated by Django 2.2.6 on 2019-10-31 19:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0002_auto_20191016_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordersystem.CustomerAccount')),
            ],
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 19, 15, 22, 299529, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='OrderSystem',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer_cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordersystem.Cart'),
        ),
    ]
