# Generated by Django 2.2.6 on 2019-10-31 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0003_auto_20191031_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='customer_cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 19, 18, 8, 26770, tzinfo=utc)),
        ),
    ]
