# Generated by Django 2.2.6 on 2019-11-04 04:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0004_auto_20191031_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='orders',
            field=models.ManyToManyField(to='ordersystem.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 4, 17, 59, 634938, tzinfo=utc)),
        ),
    ]
