# Generated by Django 2.2.6 on 2019-11-11 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0007_auto_20191104_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 0, 3, 40, 97390, tzinfo=utc)),
        ),
    ]
