# Generated by Django 2.2.6 on 2019-11-11 00:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0008_auto_20191111_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='orders',
            field=models.ManyToManyField(blank=True, to='ordersystem.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 0, 5, 44, 205496, tzinfo=utc)),
        ),
    ]
