# Generated by Django 2.2.6 on 2019-11-11 01:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0009_auto_20191111_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory_count',
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ItemCartRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersystem.Cart')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersystem.InventoryItem')),
            ],
        ),
    ]
