# Generated by Django 2.2.6 on 2019-11-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0013_auto_20191117_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
    ]
