# Generated by Django 2.2.8 on 2019-12-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0014_auto_20191117_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=27),
        ),
    ]
