# Generated by Django 2.2.6 on 2019-11-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0017_auto_20191122_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordersystem.Cart'),
        ),
    ]
