# Generated by Django 2.2.8 on 2019-12-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0019_auto_20191205_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcartrelationship',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
