# Generated by Django 2.2.8 on 2019-12-05 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0021_auto_20191205_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
